services:
    dev-db:
        image: mongo:latest
        container_name: praxtive-dev-db
        command: ["--replSet", "rs0", "--bind_ip_all"]
        ports:
          - "10000:27017"
        volumes:
          - dev-db-data:/data/db

    test-db:
        image: mongo:latest
        container_name: praxtive-test-db
        command: ["--replSet", "rs0", "--bind_ip_all"]
        ports:
          - "10010:27017"
        tmpfs:
          - /data/db

volumes:
    dev-db-data:
